# Generated by Django 2.1.7 on 2019-07-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_formula', models.CharField(max_length=200)),
                ('_vietnam_equivalent', models.CharField(max_length=200)),
                ('_english_equivalent', models.CharField(max_length=200)),
                ('_unit', models.IntegerField(default=0)),
                ('_japan_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N5', max_length=200)),
                ('_day_down', models.IntegerField(default=1)),
                ('_day_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_vietnam_meaning', models.CharField(max_length=200)),
                ('_grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.Grammar')),
            ],
        ),
    ]
