# Generated by Django 2.1.7 on 2019-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='_content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
