# Generated by Django 2.1.7 on 2019-02-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=200)),
                ('kanji_meaning', models.CharField(max_length=200)),
                ('remember_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana_form', models.CharField(max_length=200)),
                ('kanji_form', models.CharField(max_length=200)),
                ('meaning_form', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japan.Kanji')),
            ],
        ),
    ]
