# Generated by Django 2.1.7 on 2019-03-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='remember_score',
            field=models.IntegerField(default=0),
        ),
    ]
