# Generated by Django 2.1.7 on 2019-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0003_kanji_strokes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='day_down',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kanji',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
