# Generated by Django 2.1.7 on 2019-05-14 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0005_kanji_day_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastTimeReview', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('NextTimeReview', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 7, 40, 0, 600555))),
            ],
        ),
    ]
