# Generated by Django 2.2.6 on 2019-11-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0008_kanji_kanji_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='kanji_explain',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
