# Generated by Django 2.2.9 on 2020-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0009_auto_20191124_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeReview',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='day_count',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='day_down',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='remember_point',
        ),
        migrations.RemoveField(
            model_name='word',
            name='remember_score',
        ),
        migrations.AddField(
            model_name='kanji',
            name='other_information',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='review_time',
            field=models.DateTimeField(null=True),
        ),
    ]
