# Generated by Django 2.2.9 on 2020-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0010_auto_20200503_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
