# Generated by Django 2.2.9 on 2020-05-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0012_auto_20200505_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='other_information',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
