# Generated by Django 2.2.9 on 2020-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0013_auto_20200505_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereset',
            name='kanji_list',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='timereset',
            name='kanji_original_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
