# Generated by Django 2.2.9 on 2020-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0014_auto_20200505_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereset',
            name='kanji_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
